"""Plans routes — select, extend, lock, and view career plans generated by AI."""

from app import app, db, groq_client, login_required, csrf_required, check_rate_limit, run_boot_ddl
from flask import render_template, redirect, request, session, jsonify
import json
from concurrent.futures import ThreadPoolExecutor, as_completed
from services.ai import parse_ai_json

def init_db():
    """Create the locked_plans table if it does not exist."""
    run_boot_ddl("""
        CREATE TABLE IF NOT EXISTS locked_plans (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL UNIQUE,
            basic_plan TEXT NOT NULL,
            extended_plan TEXT,
            locked_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
init_db()

def get_locked_plan(user_id):
    """Retrieve a user's locked plan (basic + extended) from the database, or None."""
    rows = db.execute("SELECT * FROM locked_plans WHERE user_id = ?", user_id)
    if not rows:
        return None
    row = rows[0]
    return {
        "basic": json.loads(row["basic_plan"]),
        "extended": json.loads(row["extended_plan"]) if row["extended_plan"] else None,
        "locked_at": row["locked_at"],
    }

@app.route("/plan/select", methods=["POST"])
@login_required
def plan_select():
    """Store the user's chosen suggestion in session and check lock status."""
    suggestion = request.get_json(silent=True) or {}
    if not suggestion.get("title"):
        return jsonify({"error": "Invalid suggestion"}), 400

    session["pending_plan"] = suggestion
    session.pop("pending_extended_plan", None)
    session.modified = True

    user_id = session["user_id"]

    locked = db.execute(
        "SELECT locked FROM users WHERE id = ?",
        user_id
    )

    session["locked"] = locked[0]["locked"] if locked else 0

    return jsonify({"redirect": "/plan/extend"})


@app.route("/plan/extend")
@login_required
def plan_extend():
    """Render the extended plan page for the user's selected suggestion."""
    plan = session.get("pending_plan")

    if not plan:
        return redirect("/advice")

    user_id = session["user_id"]

    locked = db.execute(
        "SELECT locked FROM users WHERE id = ?",
        user_id
    )

    locked_value = locked[0]["locked"] if locked else 0

    already = db.execute(
        "SELECT id FROM locked_plans WHERE user_id = ?",
        user_id
    )
    if already:
        locked_value = 1

    user = db.execute(
        "SELECT name, plan_access FROM users WHERE id = ?",
        user_id
    )

    username = user[0]["name"] if user else "User"
    plan_access = user[0]["plan_access"] if user else 0

    return render_template(
        "plan_extend.html",
        username=username,
        suggestion=plan,
        locked=locked_value,
        plan_access=plan_access
    )


def call_ai_for_section(prompt, section_name, fallback_data):
    """Call the AI for a specific plan section and return parsed JSON, or fallback data on failure."""
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}],
            timeout=40.0
        )
        raw = response.choices[0].message.content.strip()
        result = parse_ai_json(raw)
        if isinstance(result, dict):
            return result
        return fallback_data
    except Exception as e:
        print(f"AI error for {section_name}: {e}")
        return fallback_data


@app.route("/generate_extended_plan", methods=["POST"])
@login_required
def generate_extended_plan():
    """Generate a detailed 6-month plan by calling AI for each section separately.

    The generation is split into focused modular prompts so each response stays
    coherent and detailed.  Earlier sections feed CONTEXT into later prompts so
    the whole plan reads as one cohesive strategy rather than disjointed chunks.
    """
    user_id = session["user_id"]
    if not check_rate_limit(f"ai:plan:{user_id}", max_attempts=5, window=3600):
        return jsonify({"error": "AI rate limit exceeded. Please wait before generating a new plan."}), 429
    profile = session.get("career_profile", "")
    suggestion = session.get("pending_plan")
    if not profile or not suggestion:
        return jsonify({"error": "Missing profile or selected path."}), 400

    # Return cached plan if already generated this session
    if session.get("pending_extended_plan"):
        return jsonify({"plan": session["pending_extended_plan"]})

    suggestion_text = json.dumps(suggestion, indent=2)
    path_title = suggestion.get("title", "Career Path")
    roadmap_steps = suggestion.get("roadmap", [])
    import re as _re
    _year_m = _re.search(r'(\d+)\s*(year|yr)', path_title, _re.IGNORECASE)
    if _year_m:
        num_months = min(int(_year_m.group(1)) * 12, 12)
    else:
        num_months = min(max(len(roadmap_steps), 3), 6)

    # ------------------------------------------------------------------
    # 1. BASIC PLAN  (title, summary, timeline, next 48h action)
    # ------------------------------------------------------------------
    basic_prompt = f"""You are a practical career strategist. A user chose this path: "{path_title}"

USER PROFILE:
{profile}

SELECTED PATH SUMMARY:
{suggestion_text}

Generate ONLY the basic plan information. Be extremely specific to their situation — include real-world examples.

Respond ONLY with valid JSON (no markdown):
{{
  "title": "{path_title}",
  "summary": "3-4 sentences on why this path works for them specifically. Reference their actual country, budget, time, education, and current skills. Include a concrete example of someone similar who succeeded.",
  "timeline_months": {num_months},
  "next_action": {{
    "what": "The single most important thing to do in the next 48 hours",
    "how": "Step-by-step instructions (5-8 concrete steps) on exactly how to do it — include specific websites to visit, exact search queries to use, what to click, what to write",
    "time_needed": "Estimated time in hours",
    "free_tools": ["tool 1 with exact website URL", "tool 2 with exact website URL"],
    "example_output": "A realistic example of what their finished output should look like — include a mock screenshot description or sample text they should have produced"
  }}
}}

Rules:
- next_action.how must be so specific they can follow it blindfolded: 'Go to website.com, click "Sign Up", fill in X with Y, then click Download'
- Include realistic example output text they can compare their work against
- Reference their country's specific platforms, job boards, or learning resources"""
    basic_data = call_ai_for_section(basic_prompt, "basic info", {
        "title": path_title,
        "summary": suggestion.get("fit", "A structured path based on your profile."),
        "timeline_months": num_months,
        "next_action": {
            "what": suggestion.get("roadmap", ["Start today"])[0] if suggestion.get("roadmap") else "Review your first step.",
            "how": "1. Open your browser and go to example.com\n2. Click 'Get Started'\n3. Create a free account using your email\n4. Complete the introductory tutorial\n5. Save your progress and share it with a friend for accountability",
            "time_needed": "2 hours",
            "free_tools": ["example.com (free learning platform)", "notion.so (free notes)"],
            "example_output": "You should have: (1) A completed account on example.com, (2) At least 3 notes saved in Notion summarizing what you learned, (3) A screenshot of your progress to share."
        }
    })

    # Build context string for downstream prompts
    basic_context = f"""Plan title: {basic_data.get('title', path_title)}
Summary: {basic_data.get('summary', '')}
Next 48h action: {basic_data.get('next_action', {}).get('what', '') if isinstance(basic_data.get('next_action'), dict) else basic_data.get('next_action', '')}"""

    # ------------------------------------------------------------------
    # 2. WEEKLY HABITS + DAILY SCHEDULE TEMPLATE
    # ------------------------------------------------------------------
    habits_prompt = f"""You are a practical career strategist. User is pursuing: "{path_title}"

USER PROFILE:
{profile}

CONTEXT FROM PREVIOUS SECTION:
{basic_context}

Generate ONLY weekly habits and a daily schedule template. Do NOT repeat the path title or summary.

Respond ONLY with valid JSON (no markdown):
{{
  "weekly_habits": [
    {{
      "habit": "Name of habit",
      "why": "Why this habit matters for their specific path — reference their actual situation",
      "how": "Exact method with time block, specific tool/website, trigger, and duration (e.g. 'Every morning 7-7:30am before work, open Notion, review yesterday's notes for 15 min, then spend 15 min on freeCodeCamp JavaScript module')",
      "time_per_week": "e.g. 5 hours",
      "example_completion": "Describe exactly what 'done' looks like for this habit — e.g. '3 pages of handwritten notes + 1 completed coding challenge on freeCodeCamp'",
      "tracking_method": "How to track completion using a free specific app or simple method (e.g. 'Mark an X on a paper calendar on the wall')",
      "if_miss": "What to do if they miss a day — exact recovery strategy with no-guilt mindset"
    }}
  ],
  "daily_schedule_template": {{
    "morning_block": "What to do in the morning with exact duration and example activity (e.g. '6:30-7:00am — 30 min: Review yesterday's notes + plan today's 3 priorities in a notebook')",
    "afternoon_block": "What to do in the afternoon with exact duration and example activity",
    "evening_block": "What to do in the evening with exact duration and example activity",
    "total_focus_hours_per_day": "Realistic number based on their constraints",
    "weekend_adjustment": "How weekends differ — give an example Saturday and Sunday schedule"
  }},
  "success_metrics": [
    {{
      "metric": "Measurable checkpoint with example target",
      "how_to_measure": "Exact method/tool to track it — include a sample tracking entry",
      "target_by_month": "What specific number or state to hit by which month"
    }}
  ]
}}

Rules:
- EVERY habit must include an 'example_completion' field showing what done looks like
- Include exactly 4-5 habits with concrete recovery strategies
- Reference their actual constraints (budget, job, family, location)
- Use specific free tool names and websites, not generic terms"""
    budget_prompt = f"""You are a practical career strategist. User is pursuing: "{path_title}"

USER PROFILE:
{profile}

CONTEXT:
{basic_context}

Generate ONLY a budget breakdown and cost-saving strategy. Do NOT repeat previous content.

Respond ONLY with valid JSON (no markdown):
{{
  "budget_breakdown": {{
    "total_estimated_cost": "Total USD/MAD to execute this 6-month plan",
    "can_be_done_free": true/false,
    "essential_spend": [
      {{"item": "What to spend on", "cost": "Amount", "why_essential": "Why this is worth paying for", "free_alternative": "How to get 90% of the value for free"}}
    ],
    "free_replacements": [
      {{"paid_thing": "Common paid resource", "free_replacement": "Exact free substitute", "catch": "Any limitation of the free version"}}
    ],
    "money_making_options": ["1-2 ways to earn small income while learning to fund tools"]
  }}
}}

Rules:
- If their budget is $0, set can_be_done_free to true and show exactly how
- If they have some budget, show where to spend for maximum ROI
- essential_spend should be 0-3 items max
- free_replacements should cover all common paid tools in this field
- Money-making options must be realistic for their skill level"""

    links_prompt = f"""You are a practical career strategist. User is pursuing: "{path_title}"

USER PROFILE:
{profile}

CONTEXT:
{basic_context}

Generate ONLY additional resource recommendations. Do NOT repeat any previous content or courses.

Respond ONLY with valid JSON (no markdown):
{{
  "links": [
    {{
      "name": "Resource name",
      "platform": "YouTube/Reddit/Medium/Podcast/Discord/Newsletter/etc",
      "description": "What it covers and why useful",
      "when": "When in their journey to use it (e.g. Month 1-2, or 'When stuck on X')",
      "how_to_use": "Exact way to consume this for maximum value (e.g. 'Watch 1 video per week and take notes')",
      "best_for": "Beginner/intermediate/advanced"
    }}
  ]
}}

Rules:
- Provide 5-7 resources (blogs, communities, YouTube channels, podcasts, tools, newsletters)
- No URLs — just resource name and platform
- Consider their budget (prefer free)
- Each resource must be different from previous sections
- how_to_use must be specific enough that they know exactly how to fit it into their schedule"""

    with ThreadPoolExecutor(max_workers=3) as executor:
        future_habits = executor.submit(call_ai_for_section, habits_prompt, "habits and metrics", {
            "weekly_habits": [
                {"habit": "Block focused learning time", "why": "Consistency builds skill", "how": "2 hours every evening after dinner", "time_per_week": "14 hours", "example_completion": "Completed 2 freeCodeCamp exercises + wrote 1 page of notes", "tracking_method": "Calendar blocks", "if_miss": "Do 30 min instead of skipping"}
            ],
            "daily_schedule_template": {
                "morning_block": "30 min review of previous day's notes",
                "afternoon_block": "1-2 hours focused skill practice",
                "evening_block": "30 min reading or video learning",
                "total_focus_hours_per_day": "2",
                "weekend_adjustment": "Double practice time on weekends if free"
            },
            "success_metrics": [
                {"metric": "Complete month 1 deliverable", "how_to_measure": "Checklist in notebook", "target_by_month": "Month 1"}
            ]
        })
        future_budget = executor.submit(call_ai_for_section, budget_prompt, "budget", {
            "budget_breakdown": {
                "total_estimated_cost": "$0",
                "can_be_done_free": True,
                "essential_spend": [],
                "free_replacements": [],
                "money_making_options": ["Freelance small tasks"]
            }
        })
        future_links = executor.submit(call_ai_for_section, links_prompt, "links", {
            "links": []
        })
        habits_data = future_habits.result()
        budget_data = future_budget.result()
        links_data = future_links.result()

    habits_context = "Weekly habits: " + ", ".join([h.get("habit", "") for h in habits_data.get("weekly_habits", [])])

    # ── ROUND 3: Skills + Courses + Projects (merged, single call) ──
    scp_prompt = f"""You are a practical career strategist. User is pursuing: "{path_title}"

USER PROFILE:
{profile}

CONTEXT:
{basic_context}
{habits_context}

Generate skills, courses, and portfolio projects in ONE response. Do NOT repeat content across sections.

Respond ONLY with valid JSON (no markdown):
{{
  "skills_to_build": [
    {{
      "skill": "Skill name",
      "priority": "high/medium/low",
      "why": "Why this skill is critical — include a real-world scenario",
      "how": "Exact step-by-step learning path with specific websites and time estimates",
      "free_resources": [{{"name":"Exact name with website","type":"tutorial/video/book","how_to_use":"How to use this","time_needed":"Xh"}}],
      "practice_projects": [{{"name":"Mini-project","description":"What to build","steps":["Step 1","Step 2"],"completion_criteria":"Done looks like"}}],
      "time_estimate": "X hours total",
      "certification_path": "Free cert or portfolio piece"
    }}
  ],
  "courses": [
    {{
      "name": "Course name",
      "provider": "Platform name",
      "description": "What they will learn",
      "why": "Why this course for their situation",
      "study_schedule": "X hours/week for Y weeks",
      "free_alternative": "100% free alternative"
    }}
  ],
  "portfolio_projects": [
    {{
      "name": "Project name",
      "why": "Why this matters for getting hired",
      "difficulty": "beginner/intermediate/advanced",
      "time_estimate": "X hours",
      "prerequisites": "What they need before starting",
      "step_by_step": ["Step 1","Step 2","Step 3"],
      "free_tools": ["tool1 with website"],
      "how_to_showcase": "Where to publish this"
    }}
  ]
}}

Rules:
- 5-8 skills, 4-6 courses, 2-3 portfolio projects
- All resources must be free or extremely low-cost
- Reference their country, budget, and schedule when relevant"""

    scp_data = call_ai_for_section(scp_prompt, "skills+courses+projects", {
        "skills_to_build": [],
        "courses": [],
        "portfolio_projects": []
    })

    skills_data = {"skills_to_build": scp_data.get("skills_to_build", [])}
    courses_data = {"courses": scp_data.get("courses", [])}
    projects_data = {"portfolio_projects": scp_data.get("portfolio_projects", [])}

    skills_context = "Key skills: " + ", ".join([s.get("skill", "") for s in skills_data["skills_to_build"][:4]])
    courses_context = "Courses: " + ", ".join([c.get("name", "") for c in courses_data["courses"][:3]])
    projects_context = "Projects: " + ", ".join([p.get("name", "") for p in projects_data["portfolio_projects"]])

    # ------------------------------------------------------------------
    # 6. PHASES —  generated in parallel (2 batches to avoid rate limits)
    # ------------------------------------------------------------------
    month_titles = []
    for i in range(num_months):
        if i < len(roadmap_steps):
            t = roadmap_steps[i][:60] if isinstance(roadmap_steps[i], str) else f"Month {i+1}"
        else:
            t = f"Phase {i+1}: continue advancing"
        month_titles.append(t)

    all_themes = [
        "build core foundations from scratch",
        "start creating your first real work",
        "deepen skills and tackle harder projects",
        "optimize your workflow and fill gaps",
        "prepare for real-world opportunities",
        "execute your launch or application strategy",
        "refine your approach and scale up",
        "specialize and stand out",
        "build authority and reputation",
        "mentor others and give back",
        "transition into full-time or advanced role",
        "lead and innovate in your field"
    ]
    month_themes = all_themes[:num_months]

    def gen_month(i, title):
        theme = month_themes[i] if i < len(month_themes) else "continue advancing"
        prev_title = month_titles[i-1] if i > 0 else "none (first month)"
        prompt = f"""Generate month {i+1} of {num_months} ("{title}") for "{path_title}".

User: {basic_context[:300]}
Skills: {skills_context}
Courses: {courses_context}
Previous month: {prev_title}

WEEK THEMES (differentiate each week clearly):
Week 1 — "{title} basics": learn fundamental concepts through hands-on practice.
Week 2 — "Build something real": apply week 1 knowledge to create a specific deliverable.
Week 3 — "Refine & expand": improve the deliverable, add features, or tackle a harder variant.
Week 4 — "Review & next steps": polish, test, document, and plan what comes next.

Return ONLY valid JSON (no markdown):
{{"month":{i+1},"title":"{title}","focus":"{theme}","weekly_breakdown":[{{"week":1,"theme":"{title} basics","actions":[{{"what":"concrete task","how":"exact steps with specific free websites/tools","time_estimate":"Xh","tool":"free tool name","output":"what they produce","common_mistake":"mistake specific to THIS exact task"}}],"mini_lecture":"2-3 sentence mentor insight","common_mistake":"overall week pitfall","checkpoint":"measurable verification"}}],"skills_this_month":["skill1"],"deliverable":"specific output they produce this month","resources":[{{"label":"resource name","why":"why relevant","how_to_use":"how to consume it","time_needed":"Xh"}}],"reflection_questions":["question that makes them think about progress"]}}

CRITICAL RULES:
- Week 1, 2, 3, 4 MUST have DIFFERENT themes and DIFFERENT actions
- Each week's actions must build on the previous week
- Every action.common_mistake must be specific to that exact task (not generic)
- Free tools only — include exact website names, URLs, or app names
- Be specific: instead of "learn", say "complete the first 3 modules on freecodecamp.org" """
        return call_ai_for_section(prompt, f"month {i+1}", {
            "month": i+1, "title": title,
            "focus": f"{title}: {theme}",
            "weekly_breakdown": [
                {"week": 1, "theme": f"{title} basics",
                 "actions": [{"what": f"Research {title} fundamentals", "how": "Watch introductory tutorials on YouTube and take notes on key concepts", "time_estimate": "4h", "tool": "YouTube", "output": "One-page summary of key concepts", "common_mistake": "Watching without taking notes — write down at least 5 key takeaways"}],
                 "mini_lecture": "Start with the big picture. Understanding the 'why' before the 'how' will help you prioritize what to learn first.", "common_mistake": "Trying to learn everything at once instead of focusing on the most essential 20%", "checkpoint": "Can you explain the core concept in 2-3 sentences to someone else?"},
                {"week": 2, "theme": f"Apply {title}",
                 "actions": [{"what": f"Complete a hands-on tutorial or mini-project in {title}", "how": "Follow a step-by-step guide on freecodecamp.org or similar free platform, building a small working example", "time_estimate": "6h", "tool": "Free online tutorial platform", "output": "A working mini-project or completed exercise set", "common_mistake": "Copy-pasting code without understanding — type everything manually and experiment with changes"}],
                 "mini_lecture": "Knowledge without practice fades quickly. Building something concrete, even if small, makes the concepts stick.", "common_mistake": "Getting stuck on perfection — done is better than perfect for learning", "checkpoint": "Does your mini-project run without errors and produce the expected output?"},
                {"week": 3, "theme": f"Refine {title} skills",
                 "actions": [{"what": f"Improve your {title} project or tackle a harder challenge", "how": "Add 2-3 new features to your project from week 2, or complete an intermediate-level exercise", "time_estimate": "5h", "tool": "Same tools from week 2 plus documentation sites", "output": "Enhanced project with new features or completed intermediate exercise", "common_mistake": "Adding too many features at once — pick ONE improvement and finish it completely"}],
                 "mini_lecture": "Real skill comes from iteration. Taking something from 'it works' to 'it works well' teaches more than starting something new.", "common_mistake": "Not testing edge cases — make sure your project handles unexpected inputs gracefully", "checkpoint": "Does your project handle both normal and edge cases?"},
                {"week": 4, "theme": f"Review {title} & plan ahead",
                 "actions": [{"what": f"Document your {title} work and set next milestones", "how": "Write a short summary of what you built, what you learned, and what you would do next. Save it as a portfolio entry or GitHub README.", "time_estimate": "3h", "tool": "GitHub or Google Docs", "output": "A written summary + documented project files", "common_mistake": "Skipping documentation — writing forces you to clarify your understanding and creates a portfolio asset"}],
                 "mini_lecture": "Reflection is where experience turns into expertise. Documenting your journey also builds your professional brand.", "common_mistake": "Moving on too quickly without consolidating what you learned — take 30 minutes to review everything from the month", "checkpoint": "Can you list 3 things you learned this month and 1 thing you would do differently?"}
            ],
            "skills_this_month": [title],
            "deliverable": f"Completed {title} phase with working project and documentation",
            "resources": [],
            "reflection_questions": [f"What was the hardest part of learning {title}?", "What would I do differently if I started this month again?"]
        })

    phases_list = []
    batch_size = 3
    for start in range(0, len(month_titles), batch_size):
        batch = month_titles[start:start+batch_size]
        with ThreadPoolExecutor(max_workers=batch_size) as executor:
            futures = [executor.submit(gen_month, start+i, t) for i, t in enumerate(batch)]
            for f in futures:
                phases_list.append(f.result())

    phases_data = {"phases": phases_list}

    phases_context = "Phase flow: " + " -> ".join([f"Month {p.get('month')}: {p.get('title', '')}" for p in phases_data.get("phases", [])])

    # ------------------------------------------------------------------
    # 7. NETWORKING & APPLICATION STRATEGY
    # ------------------------------------------------------------------
    networking_prompt = f"""You are a practical career strategist. User is pursuing: "{path_title}"

USER PROFILE:
{profile}

CONTEXT:
{basic_context}
{phases_context}

Generate ONLY networking and job/income application strategy. Do NOT repeat previous content.

Respond ONLY with valid JSON (no markdown):
{{
  "networking_strategy": {{
    "where_to_meet_people": ["Platform 1 with exact website", "Platform 2", "Local/community option in their region"],
    "who_to_connect_with": ["Specific type of person — e.g. 'Junior developers who got hired in the last 6 months'", "Profile of person 2"],
    "outreach_templates": [
      {{
        "scenario": "e.g. Cold LinkedIn message to someone working at their dream company",
        "template": "Exact message they can copy, paste, and personalize (keep under 150 words) — include [bracketed placeholders]",
        "why_it_works": "Psychology behind this message — why it gets replies",
        "example_response": "What a good reply looks like and how to continue the conversation"
      }}
    ],
    "content_strategy": "What exact type of content to post/share to attract opportunities — include 3 example post topics with sample opening lines",
    "example_post": "A complete example post they can adapt and post (100-150 words) with hashtags",
    "frequency": "How often to network per week with a schedule example"
  }},
  "application_strategy": {{
    "when_to_start_applying": "Which exact month to start sending applications and why",
    "resume_tips": ["3 specific tips with examples of good vs bad resume phrasing"],
    "resume_example_bullet": "Before/after example of a resume bullet point for this field",
    "where_to_apply": ["Platform 1 with exact URL", "Platform 2", "Alternative for their country"],
    "portfolio_presentation": "How to present their portfolio projects in applications — exact structure",
    "interview_prep": "Step-by-step interview prep plan using free resources, with example questions and how to structure answers using STAR method",
    "pricing_strategy": "If freelancing: what to charge at beginner, intermediate, and advanced level in their region with example project prices"
  }}
}}

Rules:
- Templates must be copy-paste ready with [bracket placeholders]
- Include example_response showing what a positive reply looks like
- Include example_post with hashtags
- All advice must be free or near-free
- Consider their specific country/region"""

    # ------------------------------------------------------------------
    # 9. PITFALLS, RISKS & CONTINGENCY PLANS
    # ------------------------------------------------------------------
    risks_prompt = f"""You are a practical career strategist. User is pursuing: "{path_title}"

USER PROFILE:
{profile}

CONTEXT:
{basic_context}
{phases_context}

Generate ONLY pitfalls and risks with detailed prevention and recovery. Do NOT repeat any previous content.

Respond ONLY with valid JSON (no markdown):
{{
  "pitfalls": [
    {{
      "pitfall": "Common mistake",
      "why_it_happens": "Psychological or situational reason someone in their position falls into this",
      "how_to_avoid": "Concrete prevention strategy with daily/weekly tactic",
      "recovery": "What to do if they already fell into it — step-by-step recovery"
    }}
  ],
  "risks": [
    {{
      "risk": "Honest risk",
      "likelihood": "high/medium/low",
      "impact": "high/medium/low",
      "mitigation": "How to reduce the chance",
      "contingency_plan": "What to pivot to if this risk becomes reality"
    }}
  ],
  "motivation_system": {{
    "weekly_review ritual": "Exact ritual to do every Sunday to stay motivated",
    "accountability_method": "How to hold themselves accountable with no coach",
    "reward_system": "Small rewards to attach to milestones"
  }}
}}

Rules:
- Pitfalls should be specific to their situation (education level, budget, location, time constraints)
- Each pitfall must have a recovery plan, not just prevention
- Risks must have a real contingency_plan (a Plan B they can actually execute)
- Do not repeat content from phases or skills"""

    with ThreadPoolExecutor(max_workers=2) as executor:
        future_networking = executor.submit(call_ai_for_section, networking_prompt, "networking", {
            "networking_strategy": {
                "where_to_meet_people": ["LinkedIn", "Twitter/X", "Local meetups"],
                "who_to_connect_with": ["People 1-2 years ahead"],
                "outreach_templates": [],
                "content_strategy": "Share learnings publicly",
                "frequency": "2 connections per week"
            },
            "application_strategy": {
                "when_to_start_applying": "Month 4",
                "resume_tips": ["Highlight projects"],
                "where_to_apply": ["LinkedIn Jobs", "Indeed"],
                "interview_prep": "Practice common questions",
                "pricing_strategy": "Research market rates"
            }
        })
        future_risks = executor.submit(call_ai_for_section, risks_prompt, "risks", {
            "pitfalls": [
                {"pitfall": "Requires consistency", "why_it_happens": "Life gets busy", "how_to_avoid": "Calendar blocks", "recovery": "Resume next day, don't restart"}
            ],
            "risks": [
                {"risk": "Competition", "likelihood": "medium", "impact": "medium", "mitigation": "Build unique projects", "contingency_plan": "Target niche companies"}
            ],
            "motivation_system": {
                "weekly_review ritual": "Sunday 30-min review of wins and plan next week",
                "accountability_method": "Public posting of weekly progress",
                "reward_system": "Movie night after monthly deliverable"
            }
        })
        networking_data = future_networking.result()
        risks_data = future_risks.result()

    # ------------------------------------------------------------------
    # Combine all sections into one plan dict
    # ------------------------------------------------------------------
    extended = {
        **basic_data,
        **habits_data,
        **skills_data,
        **courses_data,
        **projects_data,
        **phases_data,
        **networking_data,
        **budget_data,
        **risks_data,
        **links_data
    }

    session["pending_extended_plan"] = extended
    return jsonify({"plan": extended})


@app.route("/plan/lock", methods=["POST"])
@login_required
@csrf_required
def plan_lock():
    """Persist the user's basic + extended plan to the locked_plans table."""
    session["locked"] = 1
    
    user_id = session["user_id"]
    basic = session.get("pending_plan")
    extended = session.get("pending_extended_plan")
    if not basic or not extended:
        return redirect("/advice")

    existing = db.execute("SELECT id FROM locked_plans WHERE user_id = ?", user_id)
    if existing:
        db.execute(
            "UPDATE locked_plans SET basic_plan = ?, extended_plan = ?, locked_at = CURRENT_TIMESTAMP WHERE user_id = ?",
            json.dumps(basic), json.dumps(extended), user_id
        )
    else:
        db.execute(
            "INSERT INTO locked_plans (user_id, basic_plan, extended_plan) VALUES (?, ?, ?)",
            user_id, json.dumps(basic), json.dumps(extended)
        )

    session.pop("pending_plan", None)
    session.pop("pending_extended_plan", None)
    db.execute("UPDATE users SET locked = 1 WHERE id = ?", user_id)
    return redirect("/")


@app.route("/plan")
@login_required
def plan_view():
    """Render the user's locked plan details."""
    locked_plan = get_locked_plan(session["user_id"])
    if not locked_plan:
        return redirect("/advice")
    user = db.execute("SELECT name FROM users WHERE id = ?", session["user_id"])
    username = user[0]["name"] if user else "User"
    locked_value = 1 if locked_plan else 0
    suggestion = locked_plan["extended"] or locked_plan["basic"]
    return render_template("plan_extend.html", username=username, suggestion=suggestion, locked=locked_value, plan_data=locked_plan["extended"] or locked_plan["basic"], plan=locked_plan)


@app.route("/plan/leave", methods=["POST"])
@login_required
@csrf_required
def plan_leave():
    """Delete the user's locked plan and reset their locked status."""
    db.execute("DELETE FROM locked_plans WHERE user_id = ?", session["user_id"])
    db.execute("UPDATE users SET locked = 0 WHERE id = ?", session["user_id"])
    session.pop("pending_plan", None)
    session.pop("pending_extended_plan", None)
    return redirect("/")
